[package]
name = "sc-delegation-rs"
version = "0.1.1"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wasm"
path = "src/lib.rs"


[dependencies]
# elrond-wasm = "0.1.1"
# elrond-wasm-node = "0.1.1"
# elrond-wasm-derive = "0.1.1"

elrond-wasm = { path = "../elrond-wasm-rs/elrond-wasm" }
elrond-wasm-node = { path = "../elrond-wasm-rs/elrond-wasm-node" }
elrond-wasm-derive = { path = "../elrond-wasm-rs/elrond-wasm-derive" }
