[package]
name = "node-storage"
version = "0.4.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2018"
[dependencies.multiversx-sc]
version = "0.39.4"
[dev-dependencies.multiversx-sc-scenario]
version = "0.39.4"
