[contracts.full]
name = "delegation_latest_full"
add-labels = ["init"]

[contracts.update]
name = "delegation_latest_update"
add-labels = ["upgrade"]

[[proxy]]
path = "../interactor/src/latest_proxy.rs"
add-labels = ["init", "upgrade"]

[[proxy.path-rename]]
from = "user_fund_storage::types::fund_item::FundItem"
to = "user_fund_storage::types::FundItem"

[[proxy.path-rename]]
from = "multiversx_sc::types::io::operation_completion_status::OperationCompletionStatus"
to = "multiversx_sc::types::OperationCompletionStatus"
