[package]
name = "delegation-latest-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.delegation_latest]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.58.0"
default-features = false
