[package]
name = "auction-mock-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2018"
publish = false

[dependencies.auction-mock]
path = ".."

[dependencies.elrond-wasm]
version = "0.23.0"

[dependencies.elrond-wasm-debug]
version = "0.23.0"
