[package]
name = "user-fund-storage"
version = "0.5.8"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"

[dependencies.multiversx-sc]
version = "=0.64.0"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.64.0"
